"use client";
import Image from "next/image";
import Link from "./locale-link";
import { useState } from "react";
import { useCart } from "./cart-store";
import { useFavorites } from "./favorite-store";
import { LanguageSwitcher,useI18n } from "./i18n-provider";
import PwaInstall from "./pwa-install";
import ThemeSwitcher from "./theme-switcher";
import MegaMenu from "./mega-menu";
function IconMenu({open}:{open:boolean}){return <span className="relative block h-5 w-6" aria-hidden="true"><span className={"absolute left-0 top-1 block h-px w-6 bg-current transition "+(open?"translate-y-2 rotate-45":"")}/><span className={"absolute left-0 top-3 block h-px w-6 bg-current transition "+(open?"opacity-0":"")}/><span className={"absolute left-0 top-5 block h-px w-6 bg-current transition "+(open?"-translate-y-2 -rotate-45":"")}/></span>}
export default function SiteHeader(){const [open,setOpen]=useState(false);const {count}=useCart();const {ids}=useFavorites();const {t,number}=useI18n();const links=[[t("nav.menu"),"/menu"],[t("nav.reserve"),"/reserver"],[t("nav.favorites"),"/favoris"],[t("nav.order"),"/commande"],[t("nav.account"),"/compte"],[t("nav.contact"),"/contact"]];return <>
<header className="sticky top-0 z-50 px-3 py-2 sm:px-5"><div className="mx-auto flex max-w-7xl items-center gap-2 rounded-2xl border border-[color:var(--border)] bg-[color:var(--header)] px-3 py-2.5 text-[color:var(--header-text)] shadow-[0_18px_48px_rgba(0,0,0,.12)] backdrop-blur-xl sm:px-5">
<Link href="/" onClick={()=>setOpen(false)} className="flex min-w-0 shrink-0 items-center gap-2.5" aria-label="LA SHISH"><span className="brand-logo-shell relative flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full border border-[#d4b273]/65 bg-[#11100e] sm:h-14 sm:w-14"><Image src="/logo.webp" alt="La Shish" width={72} height={72} priority unoptimized className="brand-logo h-10 w-10 rounded-full object-cover sm:h-12 sm:w-12"/></span><span className="hidden text-xs font-black tracking-[.2em] sm:block">{t("brand")}</span></Link>
<nav className="hidden flex-1 items-center justify-center gap-4 text-[12px] font-semibold text-[color:var(--header-muted)] xl:flex">{links.map(([label,href])=><Link key={href} href={href} className="transition hover:text-[#d4b273]">{label}{href==="/favoris"&&ids.length?<span className="ms-1 rounded-full bg-[#d4b273] px-1.5 py-0.5 text-[9px] font-black text-[#11100e]">{number(ids.length)}</span>:null}{href==="/commande"&&count?<span className="ms-1 rounded-full bg-[#d4b273] px-1.5 py-0.5 text-[9px] font-black text-[#11100e]">{number(count)}</span>:null}</Link>)}</nav>
<div className="ms-auto flex items-center gap-2"><div className="hidden lg:block"><ThemeSwitcher/></div><div className="hidden md:block"><LanguageSwitcher/></div><div className="hidden min-[420px]:block"><PwaInstall/></div><Link href="/commande" className="hidden rounded-full border border-[#d4b273]/40 bg-[#d4b273]/10 px-3 py-2 text-[10px] font-black text-[#d4b273] sm:block">{t("nav.cart")} {count>0?"("+number(count)+")":""}</Link><button aria-label={open?t("nav.close"):t("nav.open")} aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex h-11 w-11 items-center justify-center rounded-xl border border-[color:var(--border)] bg-[color:var(--surface)] transition hover:scale-105 hover:border-[#d4b273]/50 hover:text-[#d4b273]"><IconMenu open={open}/></button></div>
</div></header><MegaMenu open={open} onClose={()=>setOpen(false)}/></>}
