
import type { Locale } from "./menu-localization";

const exact: Record<string, Record<"en"|"ar", string>> = {
  "Café expresso continental": { en:"Continental espresso", ar:"إسبريسو كونتيننتال" },
  "Café expresso Illy": { en:"Illy espresso", ar:"إسبريسو إيلي" },
  "Tasse de Nescafé": { en:"Nescafé cup", ar:"فنجان نسكافيه" },
  "Café Americano": { en:"Americano coffee", ar:"قهوة أمريكانو" },
  "Café Macchiato": { en:"Macchiato coffee", ar:"قهوة ماكياتو" },
  "Café Latté": { en:"Latte coffee", ar:"قهوة لاتيه" },
  "Lait chaud ou froid": { en:"Hot or cold milk", ar:"حليب ساخن أو بارد" },
  "Infusion au gingembre": { en:"Ginger infusion", ar:"منقوع الزنجبيل" },
  "Thé moyen": { en:"Medium tea", ar:"شاي متوسط" },
  "Grand thé": { en:"Large tea", ar:"شاي كبير" },
  "Eau minérale 0.5L": { en:"Mineral water 0.5L", ar:"مياه معدنية ٠٫٥ لتر" },
  "Eau minérale 1.5L": { en:"Mineral water 1.5L", ar:"مياه معدنية ١٫٥ لتر" },
  "Jus Ivorio": { en:"Ivorio juice", ar:"عصير إيفوريو" },
  "Sucrerie plastique": { en:"Soft drink (plastic bottle)", ar:"مشروب غازي (زجاجة بلاستيكية)" },
  "Sucrerie canette": { en:"Soft drink (can)", ar:"مشروب غازي (علبة)" },
  "Tournée de liqueur": { en:"Liqueur round", ar:"جولة مشروبات" },
  "Cocktail de fruits en morceaux": { en:"Fruit cocktail", ar:"كوكتيل فواكه مقطعة" },
  "Smoothie thé aux fruits rouges": { en:"Red berry tea smoothie", ar:"سموثي الشاي والتوت الأحمر" },
  "Smoothie coco": { en:"Coconut smoothie", ar:"سموثي جوز الهند" },
  "Smoothie au choix": { en:"Smoothie of your choice", ar:"سموثي حسب اختيارك" },
  "Muffin shake myrtille": { en:"Blueberry muffin shake", ar:"ميلك شيك مافن بالتوت الأزرق" },
  "Milk-shake au choix": { en:"Milkshake of your choice", ar:"ميلك شيك حسب اختيارك" },
  "Frappé ananas-coco": { en:"Pineapple-coconut frappé", ar:"فرابيه الأناناس وجوز الهند" },
  "Frappé Mojito": { en:"Mojito frappé", ar:"فرابيه موهيتو" },
  "Frappé Bastille": { en:"Bastille frappé", ar:"فرابيه باستيل" },
  "Peach tea": { en:"Peach tea", ar:"شاي بالخوخ" },
  "Thé framboise": { en:"Raspberry iced tea", ar:"شاي مثلج بالتوت" },
  "Thé mangue": { en:"Mango iced tea", ar:"شاي مثلج بالمانجو" },
  "Mojito fraise": { en:"Strawberry mojito", ar:"موهيتو الفراولة" },
  "Mojito passion": { en:"Passion fruit mojito", ar:"موهيتو الباشن فروت" },
  "Mojito mangue": { en:"Mango mojito", ar:"موهيتو المانجو" },
  "Limo ananas": { en:"Pineapple lemonade", ar:"ليمونادة بالأناناس" },
  "Limo fraise": { en:"Strawberry lemonade", ar:"ليمونادة بالفراولة" },
  "Limo mangue": { en:"Mango lemonade", ar:"ليمونادة بالمانجو" },
  "Limo passion": { en:"Passion fruit lemonade", ar:"ليمونادة بالباشن فروت" },
  "Pina Colada": { en:"Piña Colada", ar:"بينا كولادا" },
  "Tiki banane": { en:"Banana Tiki", ar:"تيكي الموز" },
  "Curacao Island": { en:"Curaçao Island", ar:"جزيرة كوراكاو" },
  "Dream Shoot": { en:"Dream Shot", ar:"دريم شوت" },
  "Citrik Shoot": { en:"Citrik Shot", ar:"سيترِك شوت" },
  "Crêpe nature": { en:"Plain crêpe", ar:"كريب سادة" },
  "Crêpe au sucre": { en:"Sugar crêpe", ar:"كريب بالسكر" },
  "Crêpe au chocolat": { en:"Chocolate crêpe", ar:"كريب بالشوكولاتة" },
  "Crêpe au Nutella": { en:"Nutella crêpe", ar:"كريب نوتيلا" },
  "Crêpe choco-banane": { en:"Chocolate banana crêpe", ar:"كريب بالشوكولاتة والموز" },
  "Crêpe aux fruits": { en:"Fruit crêpe", ar:"كريب بالفواكه" },
  "Crêpe jambon-fromage": { en:"Ham and cheese crêpe", ar:"كريب بالجبن واللحم المدخن" },
  "Banane choco": { en:"Chocolate banana", ar:"موز بالشوكولاتة" },
  "Dame blanche": { en:"Dame blanche", ar:"ديم بلانش" },
  "Coupe USA": { en:"USA sundae", ar:"آيس كريم أمريكا" },
  "Chocolat liégeois": { en:"Chocolate Liège sundae", ar:"آيس كريم لييج بالشوكولاتة" },
  "Chocolat mou": { en:"Soft chocolate sundae", ar:"آيس كريم شوكولاتة كريمي" },
  "Banana split": { en:"Banana split", ar:"بانانا سبليت" },
  "Hommos": { en:"Hummus", ar:"حمص" },
  "Hommos à la viande": { en:"Hummus with meat", ar:"حمص باللحم" },
  "M'tabal": { en:"Moutabal", ar:"متبل" },
  "M'tabal à la viande": { en:"Moutabal with meat", ar:"متبل باللحم" },
  "Portion d'alloco aux œufs durs": { en:"Fried plantain with boiled eggs", ar:"ألوكو مع البيض المسلوق" },
  "Portion d'alloco": { en:"Fried plantain", ar:"ألوكو" },
  "Portion de frites": { en:"French fries", ar:"بطاطس مقلية" },
  "Taboulé": { en:"Tabbouleh", ar:"تبولة" },
  "Fatouche": { en:"Fattoush", ar:"فتوش" },
  "Salade choux": { en:"Cabbage salad", ar:"سلطة الملفوف" },
  "Salade niçoise": { en:"Niçoise salad", ar:"سلطة نيسواز" },
  "Salade du chef au poulet": { en:"Chef chicken salad", ar:"سلطة الشيف بالدجاج" },
  "Salade thon aux œufs durs": { en:"Tuna salad with boiled eggs", ar:"سلطة التونة مع البيض المسلوق" },
  "Avocat au thon": { en:"Avocado with tuna", ar:"أفوكادو بالتونة" },
  "Cocktail d'avocat aux crevettes": { en:"Avocado shrimp cocktail", ar:"كوكتيل الأفوكادو والجمبري" },
  "Salade Shish": { en:"Shish salad", ar:"سلطة شيش" },
  "Avocat crevettes": { en:"Avocado with shrimp", ar:"أفوكادو بالجمبري" },
  "Formule Express": { en:"Express breakfast", ar:"وجبة إكسبريس" },
  "Formule LA SHISH": { en:"LA SHISH breakfast", ar:"وجبة LA SHISH" },
  "Formule Croque": { en:"Croque breakfast", ar:"وجبة كروك" },
  "Omelette nature ou œuf au plat": { en:"Plain omelette or fried egg", ar:"أومليت سادة أو بيض مقلي" },
  "Omelette tomate oignon": { en:"Tomato and onion omelette", ar:"أومليت بالطماطم والبصل" },
  "Omelette jambon fromage": { en:"Ham and cheese omelette", ar:"أومليت بالجبن واللحم المدخن" },
  "Club sandwich au jambon": { en:"Ham club sandwich", ar:"كلوب ساندويتش باللحم المدخن" },
  "Club sandwich poulet": { en:"Chicken club sandwich", ar:"كلوب ساندويتش بالدجاج" },
  "Manaiche zaatar (thym)": { en:"Zaatar manousheh (thyme)", ar:"مناقيش زعتر" },
  "Manaiche zaatar aux légumes": { en:"Zaatar manousheh with vegetables", ar:"مناقيش زعتر بالخضار" },
  "Manaiche légumes (tomate et oignon)": { en:"Vegetable manousheh", ar:"مناقيش بالخضار والطماطم والبصل" },
  "Manaiche fromage": { en:"Cheese manousheh", ar:"مناقيش بالجبن" },
  "Manaiche viande": { en:"Meat manousheh", ar:"مناقيش باللحم" },
  "Manaiche cocktail": { en:"Cocktail manousheh", ar:"مناقيش كوكتيل" },
  "Manaiche jambon fromage": { en:"Ham and cheese manousheh", ar:"مناقيش بالجبن واللحم المدخن" },
  "Végétarienne": { en:"Vegetarian pizza", ar:"بيتزا نباتية" },
  "Fruit de mer": { en:"Seafood pizza", ar:"بيتزا المأكولات البحرية" },
  "Quatre Saisons": { en:"Four Seasons pizza", ar:"بيتزا فور سيزونز" },
  "Spaghetti bolognaise": { en:"Spaghetti bolognese", ar:"سباغيتي بولونيز" },
  "Tagliatelles au poulet": { en:"Chicken tagliatelle", ar:"تاليياتيلي بالدجاج" },
  "Tagliatelles aux crevettes": { en:"Shrimp tagliatelle", ar:"تاليياتيلي بالجمبري" },
  "Riz aux légumes": { en:"Vegetable rice", ar:"أرز بالخضار" },
  "Riz cantonais au poulet": { en:"Chicken fried rice", ar:"أرز كانتوني بالدجاج" },
  "Riz cantonais aux crevettes": { en:"Shrimp fried rice", ar:"أرز كانتوني بالجمبري" },
  "Riz cantonais au jambon": { en:"Ham fried rice", ar:"أرز كانتوني باللحم المدخن" },
  "Riz cantonais à la viande": { en:"Beef fried rice", ar:"أرز كانتوني باللحم" },
  "Brochette shish taouk": { en:"Shish taouk skewers", ar:"أسياخ شيش طاووق" },
  "Brochette de filet": { en:"Beef fillet skewers", ar:"أسياخ فيليه لحم" },
  "Brochette kafta": { en:"Kafta skewers", ar:"أسياخ كفتة" },
  "Brochette mixte": { en:"Mixed skewers", ar:"أسياخ مشكلة" },
  "Brochette de mouton": { en:"Lamb skewers", ar:"أسياخ لحم الضأن" },
  "Plat de chawarma viande": { en:"Beef shawarma plate", ar:"طبق شاورما لحم" },
  "Plat de chawarma poulet": { en:"Chicken shawarma plate", ar:"طبق شاورما دجاج" },
  "Plat de viande mix au choix": { en:"Mixed meat plate of your choice", ar:"طبق لحوم مشكلة حسب اختيارك" },
  "Sandwich cheese-burger": { en:"Cheeseburger sandwich", ar:"ساندويتش تشيز برغر" },
  "Sandwich chicken cheese-burger": { en:"Chicken cheeseburger sandwich", ar:"ساندويتش تشيكن تشيز برغر" },
  "Cheese-burger + frites": { en:"Cheeseburger + fries", ar:"تشيز برغر + بطاطس" },
  "Chicken cheese-burger + frites": { en:"Chicken cheeseburger + fries", ar:"تشيكن تشيز برغر + بطاطس" },
  "Burger à cheval": { en:"Burger with fried egg", ar:"برغر مع بيض مقلي" },
  "Crispy chicken burger": { en:"Crispy chicken burger", ar:"برغر دجاج مقرمش" },
  "Barbecue burger": { en:"Barbecue burger", ar:"برغر باربكيو" },
  "Burger Super King": { en:"Super King burger", ar:"برغر سوبر كينغ" },
  "SHISH burger": { en:"SHISH burger", ar:"برغر شيش" },
  "Hot dog Chicago": { en:"Chicago hot dog", ar:"هوت دوغ شيكاغو" },
  "Hot dog New York": { en:"New York hot dog", ar:"هوت دوغ نيويورك" },
  "Hot dog chili": { en:"Chili hot dog", ar:"هوت دوغ تشيلي" },
  "Kebab viande": { en:"Beef kebab", ar:"كباب لحم" },
  "Kebab poulet": { en:"Chicken kebab", ar:"كباب دجاج" },
  "Sandwich chawarma": { en:"Shawarma sandwich", ar:"ساندويتش شاورما" },
  "Sandwich Francisco": { en:"Francisco sandwich", ar:"ساندويتش فرانسيسكو" },
  "Sandwich fajitas": { en:"Fajita sandwich", ar:"ساندويتش فاهيتا" },
  "Tacos poulet": { en:"Chicken tacos", ar:"تاكوس دجاج" },
  "Tacos viande": { en:"Beef tacos", ar:"تاكوس لحم" },
  "Tacos crispy": { en:"Crispy chicken tacos", ar:"تاكوس دجاج مقرمش" },
  "Fajitas viande": { en:"Beef fajitas", ar:"فاهيتا لحم" },
  "Fajitas poulet": { en:"Chicken fajitas", ar:"فاهيتا دجاج" },
  "Crevettes sautées": { en:"Sautéed shrimp", ar:"جمبري سوتيه" },
  "Poulet pané": { en:"Breaded chicken", ar:"دجاج مقرمش" },
  "1/2 poulet pané": { en:"Half breaded chicken", ar:"نصف دجاج مقرمش" },
  "Crispy chicken": { en:"Crispy chicken", ar:"دجاج مقرمش" },
  "Poulet rôti entier": { en:"Whole roasted chicken", ar:"دجاج مشوي كامل" },
  "1/2 poulet rôti": { en:"Half roasted chicken", ar:"نصف دجاج مشوي" },
  "Poulet braisé entier": { en:"Whole braised chicken", ar:"دجاج مطهو كامل" },
  "Poulet frit": { en:"Fried chicken", ar:"دجاج مقلي" },
  "Poulet frit aux légumes sautés": { en:"Fried chicken with sautéed vegetables", ar:"دجاج مقلي مع خضار سوتيه" },
  "Poulet braisé aux légumes sautés": { en:"Braised chicken with sautéed vegetables", ar:"دجاج مطهو مع خضار سوتيه" },
  "Filet de poisson": { en:"Fish fillet", ar:"فيليه سمك" },
  "Sosso braisé ou grillé": { en:"Braised or grilled Sosso fish", ar:"سمك سوسو مطهو أو مشوي" },
  "Carpe d'eau douce braisée": { en:"Braised freshwater carp", ar:"سمك شبوط مياه عذبة مطهو" },
  "Quesadilla viande": { en:"Beef quesadilla", ar:"كيساديا باللحم" },
  "Quesadilla poulet": { en:"Chicken quesadilla", ar:"كيساديا بالدجاج" },
  "Quesadilla cheese": { en:"Cheese quesadilla", ar:"كيساديا بالجبن" },
  "Arayesse viande": { en:"Meat arayes", ar:"عرايس باللحم" },
  "Arayesse fromage": { en:"Cheese arayes", ar:"عرايس بالجبن" },
  "Steak de poulet à la crème": { en:"Chicken steak with cream", ar:"ستيك دجاج بالكريمة" },
  "Steak à la crème": { en:"Steak with cream", ar:"ستيك بالكريمة" },
  "Steak américain": { en:"American steak", ar:"ستيك أمريكي" },
  "Entrecôte à la crème": { en:"Ribeye with cream", ar:"أنتركوت بالكريمة" },
  "Entrecôte américaine": { en:"American ribeye", ar:"أنتركوت أمريكية" },
  "Mouton sauté aux épices": { en:"Spiced sautéed lamb", ar:"لحم ضأن سوتيه بالتوابل" },
  "Souris d'agneau fondante à la sauce crémeuse": { en:"Tender lamb shank in creamy sauce", ar:"ساق ضأن طرية بصلصة كريمية" },
  "Thieb au poulet": { en:"Chicken thieboudienne", ar:"ثييب بالدجاج" },
  "Thieb au poisson Sosso": { en:"Sosso fish thieboudienne", ar:"ثييب بسمك سوسو" },
  "Sauce feuille au poulet": { en:"Chicken leaf sauce", ar:"صلصة أوراق بالدجاج" },
  "Soupe de poisson": { en:"Fish soup", ar:"شوربة السمك" },
  "Soupe de poulet": { en:"Chicken soup", ar:"شوربة الدجاج" },
  "1/2 Kedjenou de pondeuse": { en:"Half hen kedjenou", ar:"نصف كيدجينو دجاج" },
  "Kedjenou de pondeuse entier": { en:"Whole hen kedjenou", ar:"كيدجينو دجاج كامل" },
  "Kedjenou de pintade": { en:"Guinea fowl kedjenou", ar:"كيدجينو دجاج غيني" },
  "Kedjenou de lapin": { en:"Rabbit kedjenou", ar:"كيدجينو أرنب" },
  "Lapin sauté": { en:"Sautéed rabbit", ar:"أرنب سوتيه" },
  "Simple dose de viande": { en:"Single meat portion", ar:"كمية لحم واحدة" },
  "Double dose de viande": { en:"Double meat portion", ar:"كمية لحم مزدوجة" },
  "Menu simple dose + Frites + Boisson": { en:"Single meat menu + fries + drink", ar:"وجبة لحم واحدة + بطاطس + مشروب" },
  "Menu double dose + Frites + Boisson": { en:"Double meat menu + fries + drink", ar:"وجبة لحم مزدوجة + بطاطس + مشروب" }
};

const wordMap: Array<[string,string,string]> = [
  ["Base tomate","Tomato base","قاعدة طماطم"],["crème fraîche","fresh cream","كريمة طازجة"],["jambon","ham","لحم مدخن"],["fromage","cheese","جبن"],
  ["poulet","chicken","دجاج"],["viande","meat","لحم"],["crevettes","shrimp","جمبري"],["crevette","shrimp","جمبري"],["thon","tuna","تونة"],
  ["poisson","fish","سمك"],["champignons","mushrooms","فطر"],["champignon","mushroom","فطر"],["olive","olive","زيتون"],["oignon","onion","بصل"],
  ["poivron","bell pepper","فلفل حلو"],["carotte","carrot","جزر"],["salade","lettuce","خس"],["concombre","cucumber","خيار"],["tomate","tomato","طماطم"],
  ["œufs","eggs","بيض"],["œuf","egg","بيض"],["maïs doux","sweet corn","ذرة حلوة"],["pommes de terre","potatoes","بطاطس"],["pomme de terre","potato","بطاطس"],
  ["menthe","mint","نعناع"],["coco","coconut","جوز الهند"],["ananas","pineapple","أناناس"],["mangue","mango","مانجو"],["fraise","strawberry","فراولة"],
  ["framboise","raspberry","توت العليق"],["kiwi","kiwi","كيوي"],["citron vert","lime","ليمون أخضر"],["citron","lemon","ليمون"],["banane","banana","موز"],
  ["caramel","caramel","كراميل"],["chocolat","chocolate","شوكولاتة"],["glace vanille","vanilla ice cream","آيس كريم فانيليا"],["glace chocolat","chocolate ice cream","آيس كريم شوكولاتة"],
  ["chantilly","whipped cream","كريمة مخفوقة"],["lait","milk","حليب"],["eau gazeuse","sparkling water","مياه غازية"],["sirop","syrup","شراب مركز"],
  ["frites","fries","بطاطس مقلية"],["pain","bread","خبز"],["mayonnaise","mayonnaise","مايونيز"],["sauce barbecue","barbecue sauce","صلصة باربكيو"],
  ["ail","garlic","ثوم"],["légumes","vegetables","خضار"],["riz","rice","أرز"],["petits pois","peas","بازلاء"],["oignon vert","green onion","بصل أخضر"],
  ["brochettes","skewers","أسياخ"],["filet","fillet","فيليه"],["hommos","hummus","حمص"],["épices","spices","توابل"],["sauté","sautéed","سوتيه"],
  ["grillé","grilled","مشوي"],["grillade","grill","شواية"],["choix","choice","اختيار"],["salade de chou","cabbage salad","سلطة ملفوف"],["viande hachée","ground beef","لحم مفروم"],
  ["pain tacos","taco bread","خبز تاكو"],["Petite","Small","صغيرة"],["Moyenne","Medium","متوسطة"],["Grande","Large","كبيرة"],["thé","tea","شاي"],["jus","juice","عصير"],["eau","water","ماء"],["fraise","strawberry","فراولة"],["orange","orange","برتقال"],["pomme","apple","تفاح"],["pamplemousse","grapefruit","جريب فروت"],["passion","passion fruit","باشن فروت"],["limonade","lemonade","ليمونادة"],["myrtille","blueberry","توت أزرق"],["fruits rouges","red berries","التوت الأحمر"],["fruits","fruit","فواكه"],["purée","purée","مهروس"],["pois chiches","chickpeas","حمص"],["aubergines","eggplant","باذنجان"],["tranches","slices","شرائح"],["blanc de","chicken breast","صدر"],["assortiment","assortment","تشكيلة"],["frais","fresh","طازج"],["fraîche","fresh","طازجة"],["gazeuse","sparkling","غازية"],["sauce","sauce","صلصة"],["pâte d'ail","garlic paste","معجون الثوم"],["pain toasté","toasted bread","خبز محمص"],["steak","steak","ستيك"],["croustillant","crispy","مقرمش"],["croustillants","crispy","مقرمش"],["doux","sweet","حلو"],["entier","whole","كامل"],["moitié","half","نصف"],["haricot","beans","فاصوليا"],["haricots","beans","فاصوليا"],["pomme de terre","potato","بطاطس"],["tomate et oignon","tomato and onion","الطماطم والبصل"],["sauce blanche","white sauce","صلصة بيضاء"],["sauce caramel","caramel sauce","صلصة الكراميل"],["sauce chocolat","chocolate sauce","صلصة الشوكولاتة"],["saveur rhum","rum flavor","نكهة الروم"],["grenadine","grenadine","غرينادين"],["vodka","vodka","فودكا"],["gin","gin","جين"],["tequila","tequila","تيكيلا"],["whisky","whisky","ويسكي"]
];

function replaceTerms(value:string, locale:Locale) {
  let out=value;
  for(const [fr,en,ar] of wordMap) {
    const translated=locale==="en"?en:ar;
    out=out.split(fr).join(translated);
    out=out.split(fr.toLowerCase()).join(translated);
  }
  return out;
}

export function productName(value:string, locale:Locale) {
  if(locale==="fr") return value;
  return exact[value]?.[locale] ?? replaceTerms(value,locale);
}

export function productDescription(value:string|undefined, locale:Locale) {
  if(!value || locale==="fr") return value ?? "";
  return replaceTerms(value,locale);
}
