"use client";

import { useState } from "react";
import { useI18n } from "../../../components/i18n-provider";
import { reservationMessage,whatsappUrl } from "../../../lib/whatsapp";

export default function ReservePage(){
  const {t,locale}=useI18n(); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [date,setDate]=useState(""); const [time,setTime]=useState(""); const [party,setParty]=useState("2"); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");const popup=window.open("about:blank","_blank","noopener,noreferrer");const text=reservationMessage(locale,{name,phone,date,time,party,notes});try{const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),10000);const r=await fetch("/api/reservations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:name,customerPhone:phone,reservationDate:date,reservationTime:time,partySize:Number(party),notes})});window.clearTimeout(timeout);const data=await r.json();if(!r.ok)throw new Error(data.error||t("reserve.failed"));if(popup) popup.location.href=whatsappUrl(text); else window.location.assign(whatsappUrl(text))}catch(err){if(popup)popup.close();setError(err instanceof DOMException&&err.name==="AbortError"?t("reserve.timeout"):(err instanceof Error?err.message:t("reserve.failed")))}finally{setBusy(false)}};
  return <main className="min-h-screen bg-[#f5f0e7] px-5 pb-20 pt-32 sm:px-8 lg:px-12"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#b68a42]">{t("reserve.eyebrow")}</p><h1 className="mt-3 text-5xl font-black tracking-tight sm:text-7xl">{t("reserve.title")}</h1><p className="mt-5 max-w-2xl text-black/55">{t("reserve.desc")}</p><form onSubmit={submit} className="mt-10 rounded-[2rem] border border-black/10 bg-white/70 p-6 sm:p-10"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">{t("reserve.name")}<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name" className="mt-2 min-h-12 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]"/></label><label className="text-sm font-semibold">{t("reserve.phone")}<input required value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" inputMode="tel" className="mt-2 min-h-12 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]"/></label><label className="text-sm font-semibold">{t("reserve.date")}<input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]"/></label><label className="text-sm font-semibold">{t("reserve.time")}<input required type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]"/></label><label className="text-sm font-semibold">{t("reserve.people")}<input required type="number" min="1" max="50" value={party} onChange={e=>setParty(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]"/></label><label className="text-sm font-semibold sm:col-span-2">{t("reserve.special")}<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} className="mt-2 w-full resize-none rounded-2xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#b68a42]" placeholder={t("reserve.specialPlaceholder")}/></label></div>{error?<p className="mt-4 text-sm font-semibold text-red-700">{error}</p>:null}<button disabled={busy} type="submit" className="mt-7 min-h-12 rounded-full bg-[#11100e] px-6 py-3 text-sm font-bold text-white hover:bg-[#b68a42] hover:text-[#11100e] disabled:opacity-50">{busy?t("order.prepare"):t("reserve.send")}</button></form></div></main>;
}
